export const InterestedCategoryItems = [
  {
    id: 0,
    name: '파이썬 OX퀴즈',
    emoji: '👏',
    bookmarkCount: 123,
    collectionField: 'IT',
    memberName: '홍길동',
    quizCount: 35,
  },
  {
    id: 1,
    name: '자바스크립트 객관식 퀴즈',
    emoji: '✨',
    bookmarkCount: 87,
    collectionField: 'IT',
    memberName: '홍길동',
    quizCount: 40,
  },
  {
    id: 2,
    name: '파이썬 OX퀴즈',
    emoji: '❌',
    bookmarkCount: 123,
    collectionField: 'IT',
    memberName: '홍길동',
    quizCount: 35,
  },
  {
    id: 3,
    name: '자바스크립트 객관식 퀴즈',
    emoji: '✨',
    bookmarkCount: 87,
    collectionField: 'IT',
    memberName: '홍길동',
    quizCount: 40,
  },
  {
    id: 4,
    name: '파이썬 OX퀴즈',
    emoji: '❌',
    bookmarkCount: 123,
    collectionField: 'IT',
    memberName: '홍길동',
    quizCount: 35,
  },
  {
    id: 5,
    name: '자바스크립트 객관식 퀴즈',
    emoji: '✨',
    bookmarkCount: 87,
    collectionField: 'IT',
    memberName: '홍길동',
    quizCount: 40,
  },
]
