export const InterestedCategoryItems = [
  {
    id: 0,
    name: '파이썬 OX퀴즈',
    emoji: '👏',
    bookmarkCount: 123,
    description: 'string',
    collectionCategory: 'IT',
    solvedMemberCount: 20,
    bookmarked: true,
    totalQuizCount: 35,
    member: {
      creatorId: 0,
      creatorName: '홍길동',
    },
  },
  {
    id: 1,
    name: '자바스크립트 객관식 퀴즈',
    emoji: '✨',
    bookmarkCount: 87,
    description: 'string',
    collectionCategory: 'IT',
    solvedMemberCount: 20,
    bookmarked: true,
    totalQuizCount: 40,
    member: {
      creatorId: 0,
      creatorName: '홍길동',
    },
  },
  {
    id: 2,
    name: '파이썬 OX퀴즈',
    emoji: '❌',
    bookmarkCount: 123,
    description: 'string',
    collectionCategory: 'IT',
    solvedMemberCount: 20,
    bookmarked: true,
    totalQuizCount: 35,
    member: {
      creatorId: 0,
      creatorName: '홍길동',
    },
  },
  {
    id: 3,
    name: '자바스크립트 객관식 퀴즈',
    emoji: '✨',
    bookmarkCount: 87,
    description: 'string',
    collectionCategory: 'IT',
    solvedMemberCount: 20,
    bookmarked: true,
    totalQuizCount: 40,
    member: {
      creatorId: 0,
      creatorName: '홍길동',
    },
  },
  {
    id: 4,
    name: '파이썬 OX퀴즈',
    emoji: '❌',
    bookmarkCount: 123,
    description: 'string',
    collectionCategory: 'IT',
    solvedMemberCount: 20,
    bookmarked: true,
    totalQuizCount: 35,
    member: {
      creatorId: 0,
      creatorName: '홍길동',
    },
  },
  {
    id: 5,
    name: '자바스크립트 객관식 퀴즈',
    emoji: '✨',
    bookmarkCount: 87,
    description: 'string',
    collectionCategory: 'IT',
    solvedMemberCount: 20,
    bookmarked: true,
    totalQuizCount: 40,
    member: {
      creatorId: 0,
      creatorName: '홍길동',
    },
  },
]
