name: Vercel Deployment Notification

on:
  deployment_status:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Vercel 배포 상태: ${{ job.status }}"
          embed-title: "Deployment Status"
          embed-description: "${{ job.status == 'failure' && format('❌ 배포 실패: {0}', github.event.deployment_status.description) || '✅ 배포 성공' }}"
          embed-color: ${{ job.status == 'success' && '65280' || '16711680' }}
          embed-fields: |
            [
              {
                "name": "Commit",
                "value": "${{ github.sha }}"
              }
            ]
