export const AD_ID = {
  HOME_BANNER: 'DAN-qD4HTgamwYUzhqS1',
  COLLECTION1: 'DAN-g1w4RNe4b51VLcjZ',
  COLLECTION2: 'DAN-RmeNkhakPtDW83Fq',
  COLLECTION3: 'DAN-ub7XaORKQ85glmoA',
  QUIZ_SET: 'DAN-rVrn70U20nO3wv4X',
}
