export const AD_ID = {
  HOME_BANNER: 'DAN-X2Ecspxfy0R8NWty',
  COLLECTION1: 'DAN-SoMgEarK6fqPhexQ',
  COLLECTION2: 'DAN-ZMTkxzWj7wDgRzVL',
  COLLECTION3: 'DAN-fZQhpQhpz9WNJOpF',
  COLLECTION4: 'DAN-ij09nUiN6tcCI83i',
  COLLECTION5: 'DAN-90U6leocsB4E6S10',
  COLLECTION6: 'DAN-BYwRk8MVQXoxk6tv',
  COLLECTION7: 'DAN-WlMZNfxummLwEEQH',
  COLLECTION8: 'DAN-n37hM7BWkwKOk0H8',
  COLLECTION9: 'DAN-67qUFcmyKYGYSPuY',
  COLLECTION10: 'DAN-SuQOUxAb2pRyNpUK',
  QUIZ_SET: 'DAN-xJktQJDvzVbxXQBq',
}
