export const mockRecords = [
  {
    quizSetId: '1',
    name: '오늘의 퀴즈',
    quizCount: 20,
    score: 17,
    quizSetType: 'TODAY_QUIZ_SET',
    solvedDate: '2024-12-13T08:46:30.363Z',
  },
  {
    quizSetId: '2',
    name: '자바스크립트의 이해',
    quizCount: 20,
    score: 17,
    quizSetType: 'DOCUMENT_QUIZ_SET',
    solvedDate: '2024-12-13T08:46:30.363Z',
  },
  {
    quizSetId: '3',
    name: '오늘의 퀴즈',
    quizCount: 20,
    score: 17,
    quizSetType: 'TODAY_QUIZ_SET',
    solvedDate: '2024-12-12T08:46:30.363Z',
  },
  {
    quizSetId: '4',
    name: '자바스크립트의 이해',
    quizCount: 20,
    score: 17,
    quizSetType: 'DOCUMENT_QUIZ_SET',
    solvedDate: '2024-12-12T08:46:30.363Z',
  },
  {
    quizSetId: '5',
    name: '자바스크립트의 이해',
    quizCount: 20,
    score: 17,
    quizSetType: 'DOCUMENT_QUIZ_SET',
    solvedDate: '2024-12-12T08:46:30.363Z',
  },
]

export const quizzes = [
  {
    documentName: '최근 이슈',
    directoryName: '전공 공부',
    collectionName: null,
    quizSetType: 'TODAY_QUIZ_SET',
    id: 1,
    quizType: 'MULTIPLE_CHOICE' as Quiz.Type,
    question: '식물기반 단백질 시장에서 대기업의 참여가 늘어나는 이유는 무엇인가요?',
    options: [
      '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
      '배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
      '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이',
      '기존의 배양육이 기존방식에서 육류보다 토양이 비축된다',
    ],
    answer: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
    choseAnswer: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
    explanation: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
  },
  {
    documentName: '최근 이슈',
    directoryName: '전공 공부',
    collectionName: null,
    quizSetType: 'TODAY_QUIZ_SET',
    id: 2,
    quizType: 'MIX_UP' as Quiz.Type,
    question: '식물기반 단백질 시장에서 대기업의 참여가 늘어나는 이유는 무엇인가요?',
    answer: 'correct',
    choseAnswer: 'incorrect',
    explanation:
      '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다 기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
  },
  {
    documentName: '최근 이슈',
    directoryName: '전공 공부',
    collectionName: null,
    quizSetType: 'TODAY_QUIZ_SET',
    id: 3,
    quizType: 'MULTIPLE_CHOICE' as Quiz.Type,
    question: '식물기반 단백질 시장에서 대기업의 참여가 늘어나는 이유는 무엇인가요?',
    options: [
      '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
      '배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
      '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이',
      '기존의 배양육이 기존방식에서 육류보다 토양이 비축된다',
    ],
    answer: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
    choseAnswer: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이',
    explanation: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
  },
  {
    documentName: '최근 이슈',
    directoryName: '전공 공부',
    collectionName: null,
    quizSetType: 'TODAY_QUIZ_SET',
    id: 5,
    quizType: 'MIX_UP' as Quiz.Type,
    question: '식물기반 단백질 시장에서 대기업의 참여가 늘어나는 이유는 무엇인가요?',
    answer: 'correct',
    choseAnswer: 'correct',
    explanation: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
  },
  {
    documentName: '최근 이슈',
    directoryName: '전공 공부',
    collectionName: null,
    quizSetType: 'TODAY_QUIZ_SET',
    id: 4,
    quizType: 'MIX_UP' as Quiz.Type,
    question: '식물기반 단백질 시장에서 대기업의 참여가 늘어나는 이유는 무엇인가요?',
    answer: 'correct',
    choseAnswer: 'correct',
    explanation: '기존의 배양육이 기존방식에서 생산되는 육류보다 토양이 비축된다',
  },
]
