name: Vercel Deployment Notification

on:
  deployment_status:
    branches: [ develop ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Vercel 배포 상태: ${{ github.event.deployment_status.state }}"
          embed-title: "Deployment Status"
          embed-description: "${{ github.event.deployment_status.state == 'failure' && format('❌ 배포 실패: {0}', github.event.deployment_status.description) || (github.event.deployment_status.state == 'error' && format('❌ 배포 오류: {0}', github.event.deployment_status.description) || '✅ 배포 성공') }}"
          embed-color: ${{ github.event.deployment_status.state == 'success' && '65280' || '16711680' }}
          embed-fields: |
            [
              {
                "name": "Commit",
                "value": "${{ github.sha }}"
              },
              {
                "name": "Status",
                "value": "${{ github.event.deployment_status.state }}"
              },
              {
                "name": "Log URL",
                "value": "${{ github.event.deployment_status.log_url || 'Not available' }}"
              }
            ]
